### ISSUE TITLE
Error during recognition

### ISSUE THREAD

**Issue by cuzzysoft** [sharmaji27/face-recognition-based-attendance-system#1]
`facialattendance\app.py:111: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  if extract_faces(frame)!=():`

**Comment by sharmaji27** [comment]
This is a warning and not an error

**Comment by cuzzysoft** [comment]
The camera loops infinitely during recognition while throwing that error multiple times. Although it recognizes the face, the camera does not close down. I had to end the process from Task manager before the camera can shut down.

**Comment by sharmaji27** [comment]
This is the ideal situation.

The camera should run infinitely because people keep on coming and
attendance keeps on getting updated.

Everytime when new person comes, he/she will not run the app.

Although you can close the camera using the ESC key (I hope you would have
gone through the code once before raising the issue)

In the future update I will also add a quit button.

Hope you understood.

**Comment by cuzzysoft** [comment]
Okay no problem
